controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

weather_forecast:
    path: /weather
    controller: App\Controller\WeatherController::getWeather